name: dioptas
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - dioptas
  - fabio
  - h5py
  - ipympl=0.9.3=pyhd8ed1ab_0
  - ipywidgets=7.7.0=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.0=pyhd8ed1ab_0
  - matplotlib-base=3.5.2=py39h700656a_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - matplotlib=3.5.2=py39hf3d152e_0
  - numpy
  - mkl_fft
  - openbabel
  - pandas
  - plotly
  - pycifrw
  - pyfai
  - pymatgen
  - scikit-image
  - scikit-learn
  - scipy
