context:
  name: libnfft
  version: 3.5.3

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://www-user.tu-chemnitz.de/~potts/nfft/download/nfft-3.5.3.tar.gz
  sha256: caf1b3b3e5bf8c33a6bfd7eca811d954efce896605ecfd0144d47d0bebdf4371

build:
  script:
    - ./configure --enable-all --prefix=$PREFIX
    - make
    - make check
    - make install
  run_exports:
    - "{{ pin_subpackage('libnfft', max_pin='x.x') }}"


requirements:
  build:
    - "{{ compiler('c') }}"
    - make
  host:
    #- fftw-static >=3
    - fftw >=3

test:
  exists:
    lib:
      - nfft3
