context:
  name: metadata-client
  version: 4.1.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/metadata_client-{{ version }}.tar.gz
  sha256: d9b8ceb72ef72913e53eb4ebb846e6c37348b96d917f8f73a9a3392daa23899d

build:
  noarch: python
  script: '{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .'
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - oauthlib
    - requests
    - requests-oauthlib
    - oauth2-xfel-client >=6.1
    - pytz

test:
  imports:
    - metadata_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.xfel.eu/gitlab/ITDM/metadata_client
  summary: Python Client for European XFEL Metadata Catalogue Web App available at https://in.xfel.eu/metadata
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca

