context:
  name: zlib-into
  version: '0.4'

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zlib_into-{{ version }}.tar.gz
  sha256: 767aef73038b11bccf148d618340b926d3f80b67b51e8cf484c5d563535e6889 

build:
  script: '{{ PYTHON }} -m pip install . -vv --no-build-isolation'
  number: 0

requirements:
  build:
    - '{{ compiler("c") }}'
  host:
    - python
    - setuptools
    - pip
    - zlib
  run:
    - python
    - zlib

test:
  imports:
    - zlib_into

about:
  home: https://git.xfel.eu/dataAnalysis/zlib_into
  summary: Compress & decompress data into preallocated buffers
  license: MPL-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - RobertRosca

