#! /usr/bin/env bash

if [[ ! -z "${SASE+x}" ]]; then
    # Do nothing on the online cluster since we don't have scratch
    exit 0
fi

scratch_dir="/gpfs/exfel/data/scratch/${USER}"
scratch_depot="${scratch_dir}/julia-depot"
home_depot="${HOME}/.julia"

# Some people don't have permissions to use scratch so this may fail, in which
# case we fallback to ${home_depot}.
mkdir -p ${scratch_depot}
ret=$?

if [[ ! ${ret} -eq 0 ]]; then
    echo "Couldn't create depot in scratch, falling back to ${home_depot}"
    mkdir -p ${home_depot}
    exit 0
fi

set -euo pipefail

if [[ ! -L ${home_depot} ]] && [[ -d ${home_depot} ]]; then
    echo "Error: there is already a Julia depot at ${home_depot}. If you want to use it, please copy it to your scratch directory with this command:"
    echo "      rsync -ah --info=progress2 --exclude juliaup ${home_depot}/ ${scratch_depot}/"
    echo
    echo "And then delete ${home_depot} and make it a symlink to the scratch depot with these commands:"
    echo "      rm -rf ${home_depot}"
    echo "      ln -s ${scratch_depot} ${home_depot}"
    exit 1
fi

# If a symlink to the scratch depot doesn't exist, make one for convenience
if [[ ! -d ${home_depot} ]]; then
    ln -s ${scratch_depot} ${home_depot}
fi

exit 0

# Skip all the startup.jl stuff for now, unclear if it's a good idea

# startup_file="${scratch_depot}/config/startup.jl"
# if [[ ! -f ${startup_file} ]]; then
#     touch ${startup_file}
# fi

# block_begin='# BEGIN XFEL JULIA CONFIG'
# block_end='# END XFEL JULIA CONFIG'

# grep -q "${block_begin}" ${startup_file}
# grep_ret=$?
# if [[ ${grep_ret} -eq 0 ]]; then
#     # Delete existing block
#     sed -i "/${block_begin}/,/${block_end}/d" ${startup_file}
# else
#     # If it's the first time we're adding it, insert some whitespace
#     echo "" >> ${startup_file}
#     echo "" >> ${startup_file}
# fi

# # Insert startup block
# cat >> ${startup_file} <<EOF
# ${block_begin}

# # Don't modify the lines in this block, they're maintained by the 'exfel julia' module

# # https://timholy.github.io/Revise.jl/stable/config/#Polling-and-NFS-mounted-code-directories:-JULIA_REVISE_POLL
# using Revise
# ENV["JULIA_REVISE_POLL"] = "1"

# # https://juliapy.github.io/PythonCall.jl/stable/pythoncall/#If-you-already-have-Python-and-required-Python-packages-installed
# ENV["JULIA_CONDAPKG_BACKEND"] = "Null"
# ENV["JULIA_PYTHONCALL_EXE"] = "/gpfs/exfel/sw/software/mambaforge/22.11/envs/202402/bin/python"

# # https://juliahpc.github.io/user_gettingstarted/#set_julia_cpu_target_appropriately
# ENV["JULIA_CPU_TARGET"] = "generic;broadwell,clone_all;skylake-avx512,clone_all;cascadelake,clone_all;znver3,clone_all;znver2,clone_all"

# # Set the scratch depot
# pushfirst!(Base.DEPOT_PATH, "${scratch_depot}")

# ${block_end}
# EOF
