#! /usr/bin/env bash

if [[ ! -z "${SASE+x}" ]]; then
    # Do nothing on the online cluster since we don't have scratch
    exit 0
fi

scratch_dir="/gpfs/exfel/data/scratch/${USER}"
scratch_depot="${scratch_dir}/julia-depot"
home_depot="${HOME}/.julia"

# Some people don't have permissions to use scratch so this may fail, in which
# case we fallback to ${home_depot}.
mkdir -p ${scratch_depot}
ret=$?

if [[ ! ${ret} -eq 0 ]]; then
    echo "Couldn't create depot in scratch, falling back to ${home_depot}"
    mkdir -p ${home_depot}
    exit 0
fi

set -euo pipefail

if [[ ! -L ${home_depot} ]] && [[ -d ${home_depot} ]]; then
    echo "Error: there is already a Julia depot at ${home_depot}. If you want to use it, please copy it to your scratch directory with this command:"
    echo "      rsync -ah --info=progress2 --exclude juliaup ${home_depot}/ ${scratch_depot}/"
    echo
    echo "And then delete ${home_depot} and make it a symlink to the scratch depot with these commands:"
    echo "      rm -rf ${home_depot}"
    echo "      ln -s ${scratch_depot} ${home_depot}"
    exit 1
fi

# If a symlink to the scratch depot doesn't exist, make one for convenience
if [[ ! -d ${home_depot} ]]; then
    ln -s ${scratch_depot} ${home_depot}
fi

exit 0
