#! /usr/bin/env bash

source /usr/share/Modules/init/bash
module load exfel julia/202502

set -euxo pipefail

hostname

export JULIA_MAX_NUM_PRECOMPILE_FILES=2
export IJULIA_NODEFAULTKERNEL=1

# Update and precompile everything
julia --project=$JULIA_EXFEL_ENV -e '
import Pkg
Pkg.precompile()

import CUDA
CUDA.precompile_runtime()
'
