context:
  name: findxfel
  version: 0.1.1

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: ssh://git.xfel.eu:10022/dataAnalysis/findxfel.git
  git_depth: 1

build:
  entry_points:
    - findxfel = findxfel:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv'
  number: 0

requirements:
  host:
    - python
    - pip
    - flit-core
  run:
    - python

test:
  imports:
    - findxfel
  commands:
    - pip check
    - findxfel --help
  requires:
    - pip

about:
  home: https://git.xfel.eu/gitlab/dataAnalysis/findxfel
  summary: Find an EuXFEL proposal/run directory on Maxwell
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  notes: "'flit-core' added manually"
  recipe-maintainers:
    - RobertRosca

