context:
  name: matplotlib-scalebar
  version: 0.8.1

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matplotlib-scalebar-{{ version }}.tar.gz
  sha256: 14887af1093579c5e6afae51a0a1ecc3f715cdbc5c4d7ef59cdeec76ee6bb15d

build:
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv'
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base
    - python >=3.7

test:
  imports:
    - matplotlib_scalebar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ppinard/matplotlib-scalebar
  summary: Artist for matplotlib to display a scale bar
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca

