name: "hexrd"
channels:
  - nodefaults
  - /gpfs/exfel/sw/software/euxfel-environment-management/custom-recipes/conda-bld
  - conda-forge
  - hexrd/label/prerelease
dependencies:
  - python=3.11
  - brotlipy=0.7.0
  - certipy=0.1.3
  - ipykernel
  - ipympl
  - ipython
  - ipython_genutils
  - ipywidgets
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - pyls-spyder=0.4.0
  - scipy
  - astropy
  - bokeh
  - cudatoolkit>=11.2
  - curl
  - cython
  - dask
  - dask-jobqueue
  - dask-labextension
  - datashader
  - fabio
  - fast-histogram
  - fftw
  - h5glance>=0.8.1
  - h5netcdf
  - h5py
  - hexrd
  - hexrdgui
  - hvplot
  - imageio
  - iminuit
  - jupyterlab-lsp
  - kafka-python-ng
  - lmfit
  - mpl-interactions
  - msgpack-numpy
  - msgpack-python
  - natsort
  - netcdf4
  - numba
  - numpy
  - opencv
  - papermill
  - pint
  - plotly
  - polars
  - pyabel
  - pybaselines
  - pyfai
  - pyopengl
  - pyqtgraph
  - pytest
  - python-kaleido
  - pywavelets
  - pyzmq<25
  - scikit-beam
  - scikit-image
  - scikit-learn
  - seaborn
  - silx
    #  - tensorflow-cpu
  - tensorflow-gpu
  - xarray
  - xraylib
  - zulip
  - calibration-client >=11.3.0
  - damnit
  - envmodules
  - euxfel-bunch-pattern
  - extra-data >= 1.14
  - extra-hed
  - findxfel
  - hdf5-vds-check
  - karabo-bridge
  - karabo_bridge_recorder
  - matplotlib-scalebar
  - metadata-client
  - metropc
  - nbclick
  - pasha
  - princess
