context:
  name: spsim
  version: 1.0.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/FXIhub/spsim.git
  git_depth: 1

build:
  script:
    - mkdir build
    - cd build
    - >
      cmake \
        $CMAKE_ARGS \
        -DUSE_CUDA=OFF \
        -DUSE_NFFT=ON \
        -DBUILD_LIBRARY=ON \
        -DPYTHON_WRAPPERS=ON \
        -DCMAKE_INSTALL_PREFIX=${PREFIX} \
        -DPYTHON_INSTDIR=${SP_DIR} \
        ..
    - make
    - make install

requirements:
  build:
    - "{{ compiler('c') }}"
    - cmake
    - "{{ compiler('cxx') }}"
    - make
    - swig
  host:
    - python
    - fftw >=3
    - gsl
    - hdf5
    - libblas
    - libnfft
    - libspimage
    - numpy
  run:
    - python
    - h5py
    - "{{ pin_compatible('hdf5') }}"
    - "{{ pin_compatible('numpy') }}"
    - scipy

test:
  imports:
    - spsim
