context:
  name: damnit
  version: '0.1.3'

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/European-XFEL/damnit
  git_tag: '{{ version }}'

build:
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv'
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9
    - h5netcdf
    - h5py
    - orjson
    - pandas
    - plotly
    - xarray

test:
  imports:
    - damnit
  commands:
    - pip check
  requires:
    - pip

about:
  summary: The Data And Metadata iNspection Interactive Thing
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca

