name: extra-foam-scs
channels:
  - /gpfs/exfel/sw/software/euxfel-environment-management/custom-recipes/conda-bld
  - conda-forge
  - nodefaults
dependencies:
  # build:
  - cmake=3.25
  - libxcrypt
  # host:
  - python=3.8
  - blas
  - cython
  - numpy=1.19
  - pip
  - setuptools
  - tbb-devel=2020
  - tbb=2020
  - xsimd
  - xtensor-blas=0.20
  - xtensor-python=0.26
  - xtensor=0.24
  - xtl=0.7
  # run:
  - cffi
  - decorator
  - fabio=0.12
  - future=0.18
  - gmock=1.16
  - gtest=1.16
  - h5py=3.3
  - hiredis=1
  - imageio=2.8
  - karabo-bridge
  - msgpack-numpy=0.4
  - numpy=1.19
  - pandas=1.3
  - pillow=7
  - pybind11=2.13
  - pyfai=0.21
  - pygments
  - pyqt5-sip=12.9
  - pyqt=5.12
  - python=3.8
  - pyyaml=6.0
  - pyzmq
  - redis-py=5.2
  - scipy=1.7
  - silx=1.0
  - six=1.16
  - toolz=0.12
  - xarray=0.20
  - pip:
    - Pillow==7.*
    - extra-data==1.17.*
    - extra-geom==1.12.*
    - karabo-bridge==0.7.*
    - redis==3.5.*
