{% set name = "extra-data" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EXtra-data-{{ version }}.tar.gz
  sha256: 6b14385b897230666d349d518b4830231fa65ca8f7ec31782588aa5dad190207

build:
  entry_points:
    - lsxfel = extra_data.lsxfel:main
    - karabo-bridge-serve-files = extra_data.cli.serve_files:main
    - extra-data-validate = extra_data.validation:main
    - extra-data-make-virtual-cxi = extra_data.cli.make_virtual_cxi:main
    - extra-data-locality = extra_data.locality:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - h5py >=2.10
    - numpy
    - pandas
    - xarray

test:
  imports:
    - extra_data
  commands:
    - pip check
    - lsxfel --help
    - karabo-bridge-serve-files --help
    - extra-data-validate --help
    - extra-data-make-virtual-cxi --help
    - extra-data-locality --help
  requires:
    - pip

about:
  home: https://pypi.org/project/EXtra-data/
  summary: "Tools to read and analyse data from European XFEL"
  dev_url: https://github.com/European-XFEL/EXtra-data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca
