context:
  name: extra-data
  version: 1.14.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EXtra-data-{{ version }}.tar.gz
  sha256: 11b3b3d40c6f66e91fda2a2f396ce65d837955b258e639cad90ba63ec4bff405

build:
  entry_points:
    - lsxfel = extra_data.lsxfel:main
    - karabo-bridge-serve-files = extra_data.cli.serve_files:main
    - extra-data-validate = extra_data.validation:main
    - extra-data-make-virtual-cxi = extra_data.cli.make_virtual_cxi:main
    - extra-data-locality = extra_data.locality:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv'
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - h5py >=2.10
    - numpy
    - pandas
    - xarray
    - matplotlib
    - sel(array): dask[array]

test:
  imports:
    - extra_data
  commands:
    - pip check
    - lsxfel --help
    - karabo-bridge-serve-files --help
    - extra-data-validate --help
    - extra-data-make-virtual-cxi --help
    - extra-data-locality --help
  requires:
    - pip

about:
  home: https://pypi.org/project/EXtra-data/
  summary: Tools to read and analyse data from European XFEL
  dev_url: https://github.com/European-XFEL/EXtra-data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca

