context:
  name: extra-data
  version: 1.20.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/extra_data-{{ version }}.tar.gz
  sha256: 943eabbe9ad4b266c2dfe24c10ac0760df8ebf1e8899c56a1fb3cc2a6121c207

build:
  entry_points:
    - lsxfel = extra_data.lsxfel:main
    - karabo-bridge-serve-files = extra_data.cli.serve_files:main
    - karabo-bridge-serve-run = extra_data.cli.serve_run:main
    - extra-data-validate = extra_data.validation:main
    - extra-data-make-virtual-cxi = extra_data.cli.make_virtual_cxi:main
    - extra-data-locality = extra_data.locality:main
  noarch: python
  script: '{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .'
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - h5py >=2.10
    - numpy
    - pandas
    - xarray
    - matplotlib
    - pyyaml
    - sel(array): dask[array]

test:
  imports:
    - extra_data
  commands:
    - pip check
    - lsxfel --help
    - karabo-bridge-serve-files --help
    - karabo-bridge-serve-run --help
    - extra-data-validate --help
    - extra-data-make-virtual-cxi --help
    - extra-data-locality --help
  requires:
    - pip

about:
  home: https://pypi.org/project/EXtra-data/
  summary: Tools to read and analyse data from European XFEL
  dev_url: https://github.com/European-XFEL/EXtra-data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca

