context:
  name: libspimage
  version: 1.0.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/FXIhub/libspimage.git
  git_depth: 1

build:
  script:
    - mkdir build
    - cd build
    - >
      cmake \
        $CMAKE_ARGS \
        -DCMAKE_VERBOSE_MAKEFILE=ON \
        -DUSE_CUDA=OFF \
        -DPYTHON_WRAPPERS=ON \
        -DCMAKE_INSTALL_PREFIX=${PREFIX} \
        -DPYTHON_INSTDIR=${SP_DIR} \
        -DPYTHON_EXECUTABLE=${PYTHON} \
        ..
    - make
    - make install
  run_exports:
    - "{{ pin_subpackage('libspimage', max_pin='x.x.x') }}"

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - cmake
    - make
    - swig
  host:
    - python
    - fftw >=3
    - gsl
    - hdf5
    - libpng
    - libtiff
    - numpy
    - zlib
  run:
    - python
    - h5py
    - "{{ pin_compatible('hdf5') }}"
    - "{{ pin_compatible('numpy') }}"
    - scipy

test:
  imports:
    - spimage

  exists:
    lib:
      - spimage
