context:
  name: pasha
  version: 0.1.2

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pasha-{{ version }}.tar.gz
  sha256: 7133ae62639e3c88d18f9b16e61efda9200d1963dc49cf7019565cc5d61c6fe9

build:
  noarch: python
  script: '{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .'
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - pasha
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/European-XFEL/pasha
  summary: Tools to parallelize operations on large data sets using shared memory with zero copies.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca

