{% set name = "sharedmem" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sharedmem-{{ version }}.tar.gz
  sha256: c654a6bee2e2f35c82e6cc8b6c262fcabd378f5ba11ac9ef71530f8dabb8e2f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - sharedmem
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/rainwoodman/sharedmem
  summary: Dispatch your trivially parallizable jobs with sharedmem.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
