context:
  name: condor
  version: 1.0.7

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/FXIhub/condor.git
  git_depth: 1

build:
  script:
    - export NFFT_INCLUDE_DIR="$BUILD_PREFIX/include"
    - export NFFT_LIBRARY_DIR="$BUILD_PREFIX/lib"
    - '{{ PYTHON }} setup.py install'
  number: 0
  entry_points:
    - condor=condor.scripts.condor_script:main

requirements:
  build:
    - "{{ compiler('c') }}"
  host:
    - python
    - libnfft
    - numpy
    - spsim
  run:
    - python
    - "{{ pin_compatible('numpy') }}"
    - h5py
    - scipy
    - spsim

test:
  source_files:
    - tests/
    - examples/
  imports:
    - condor
  commands:
    - python3 -m pip check
    - condor --help
    - python3 -m pytest ./tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/FXIhub/condor
  summary: 'Condor: Simulation of single particle X-ray diffraction patterns'
  license: BSD-2-Clause
  license_file: copyright

extra:
  recipe-maintainers:
    - RobertRosca

