channels:
  - file://gpfs/exfel/sw/software/xfel_anaconda3/mambaforge-22.9/conda-bld
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - astropy
  - bokeh
  - cython
  - dask
  - dask-jobqueue
  - dask-labextension
  - fabio
  - h5py
  - imageio
  - iminuit
  - ipykernel=6.13.1
  - ipympl=0.9.3
  - ipython=7.33.0
  - ipywidgets=7.7.0
  - jupyter
  - jupyterlab=3.4.3
  - jupyterlab_widgets=1.1.0
  - kafka-python
  - lmfit
  - matplotlib=3.5.2
  - msgpack-numpy
  - msgpack-python
  - natsort
  - numba
  - numpy
  - opencv
  - plotly
  - pybaselines
  - pyfai
  - pyopengl
  - pytest
  - pywavelets
  - pyzmq
  - scikit-beam
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - silx
  - spyder
  - xarray
  - xraylib
category: base
