channels:
  - file://gpfs/exfel/sw/software/xfel_anaconda3/mambaforge-22.9/conda-bld
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - astropy
  - bokeh
  - dask
  - dask-jobqueue
  - dask-labextension
  - fabio
  - h5py
  - imageio
  - iminuit
  - ipympl=0.7.0
  - ipython
  - ipywidgets=7.6.3
  - jupyter
  - jupyterlab
  - kafka-python
  - lmfit
  - lmfit
  - mamba
  - matplotlib=3.4.2
  - msgpack-numpy
  - msgpack-python
  - numba
  - numpy
  - plotly
  - pybaselines
  - pyfai
  - pywavelets
  - pyzmq
  - scikit-beam
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - silx
  - silx
  - spyder
  - xarray
  - xraylib
