context:
  name: extra-geom
  version: 1.13.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/extra_geom-{{ version }}.tar.gz
  sha256: 848939154c38f07847243031a297adb681c40d15a4a1740b2fedc8db9e52a636

build:
  noarch: python
  script: '{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .'
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - cfelpyutils >=2.0,<3.0
    - h5py >=2.7.1
    - matplotlib-base
    - numpy

test:
  imports:
    - extra_geom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/European-XFEL/EXtra-geom
  summary: Tools to work with EuXFEL detector geometry and assemble detector images
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca

