context:
  name: extra-geom
  version: 1.9.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EXtra-geom-{{ version }}.tar.gz
  sha256: 4b4622490186146fdcb5510b7de5a1cdc1fbca9a3f0bbcf931c699d151bf724a

build:
  noarch: python
  script: '{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .'
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cfelpyutils >=2.0,<3.0
    - h5py >=2.7.1
    - matplotlib-base
    - numpy

test:
  imports:
    - extra_geom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/European-XFEL/EXtra-geom
  summary: Tools to work with EuXFEL detector geometry and assemble detector images
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca

