context:
  name: htmlgen
  version: 2.0.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/srittau/python-htmlgen/archive/v{{ version }}.tar.gz
  sha256: 891ac5a30266d658a6d4e708e53f1c4a0621a36cbdbda4c4c4e9ac09a06ea863

build:
  noarch: python
  script: '{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .'
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5

test:
  imports:
    - htmlgen
    - test_htmlgen
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/srittau/python-htmlgen
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca

