context:
  name: condat-gridconv
  version: latest

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/European-XFEL/condat-gridconv/archive/{{ version }}.tar.gz
  sha256: 2cbdf516bde34b80f7be0a56cb3dee580cfc990d07ce9a46ca0eb6bd9cf18277

build:
  script: '{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .'
  number: 0

requirements:
  build:
    - '{{ compiler("c") }}'
  host:
    - python
    - setuptools
    - wheel
    - cython
    - pip
  run:
    - python
    - "{{ pin_compatible('numpy') }}"

test:
  imports:
    - condat_gridconv
  commands:
    - pip check
  requires:
    - pip

about:
  license: ''
  dev_url: https://github.com/European-XFEL/condat-gridconv

extra:
  recipe-maintainers:
    - RobertRosca

