{% set name = "calibration-client" %}
{% set version = "11.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/calibration_client-{{ version }}.tar.gz
  sha256: 352279e76060a39097064725ac3a46bd825475da18b9c74207ff159b2c1eaf4b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - oauthlib
    - requests
    - requests-oauthlib
    - oauth2-xfel-client >=6.1
    - pytz

test:
  imports:
    - calibration_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.xfel.eu/gitlab/ITDM/calibration_client
  summary: Python Client for European XFEL Calibration Catalogue Web App available at https://in.xfel.eu/calibration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca
