context:
  name: calibration-client
  version: 11.3.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/calibration_client-{{ version }}.tar.gz
  sha256: 9d94df40a60eeaf3363848e6a2ed15c07059828a0e5e4b44afa2151fa1847b85

build:
  noarch: python
  script: '{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .'
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - oauthlib
    - requests
    - requests-oauthlib
    - oauth2-xfel-client >=6.1
    - pytz

test:
  imports:
    - calibration_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.xfel.eu/gitlab/ITDM/calibration_client
  summary: Python Client for European XFEL Calibration Catalogue Web App available at https://in.xfel.eu/calibration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca

