context:
  name: EXtra-HED
  version: 0.1.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ./src
  # git_url: ssh://git@git.xfel.eu:10022/tmichela/EXtra-HED.git
  git_depth: 1

build:
  noarch: python
  script: '{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .'
  number: 0

requirements:
  build:
    - git
  host:
    - python
    - pip
  run:
    - extra-data
    - h5py
    - numpy
    - python
    - scipy

test:
  imports:
    - extra_hed
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Analysis toolbox for the HED instrument at EuXFEL.
  license: BSD-3-Clause
  dev_url: https://git.xfel.eu/tmichela/EXtra-HED.git

extra:
  notes: Invalid license removed manually
  recipe-maintainers:
    - RobertRosca

