{% set name = "hdf5-vds-check" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hdf5_vds_check-{{ version }}.tar.gz
  sha256: d332e2f36a0b556f61845b83209bf68e708d9d198f7210313312b963f0165a13

build:
  entry_points:
    - hdf5-vds-check = hdf5_vds_check:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - flit
  run:
    - python >=3.6
    - h5py >=2.9.0

test:
  imports:
    - hdf5_vds_check
  commands:
    - pip check
    - hdf5-vds-check --help
  requires:
    - pip

about:
  home: https://github.com/European-XFEL/hdf5-vds-check
  summary: Check access to the source files of virtual datasets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  notes: `flit` added manually
  recipe-maintainers:
    - RobertRosca
