name: "202501"
channels:
  - nodefaults
  - /gpfs/exfel/sw/software/euxfel-environment-management/custom-recipes/conda-bld
  - conda-forge
dependencies:
  - python=3.11
  - certipy=0.1.3
  - ipykernel=6.29.0
  - ipympl=0.9.4
  - ipython=8.21.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - jupyter-lsp=2.2.2
  - jupyter-server-mathjax=0.2.6
  - jupyter=1.0.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.5
  - jupyter_server_terminals=0.5.2
  - jupyter_telemetry=0.1.0
  - jupyterhub-base=4.0.2
  - jupyterhub=4.0.2
  - jupyterlab-git=0.50.2
  - jupyterlab-h5web=12.3.0
  - jupyterlab=4.1.8
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - matplotlib=3.8.2
  - astropy
  - bokeh
  - curl
  - cython
  - dask
  - dask-jobqueue
  - dask-labextension
  - datashader
  - fabio
  - fast-histogram
  - fftw
  - h5glance>=0.8.1
  - h5netcdf
  - h5py
  - hvplot
  - imageio
  - iminuit
  - jupyterlab-lsp
  - kafka-python-ng
  - lmfit
  - mpl-interactions
  - msgpack-numpy
  - msgpack-python
  - natsort
  - netcdf4
  - numba
  - numpy
  - opencv
  - papermill
  - pint
  - plotly
  - polars
  - pyabel
  - pybaselines
  - pyfai
  - pyhdf
  - pyopengl
  - pyqtgraph
  - pytest
  - python-kaleido
  - pywavelets
  - pyzmq<25
  - scikit-beam
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - silx
  - spyder
  - xarray
  - xraylib
  - zulip
  - calibration-client >=11.3.0
  - cfelpyutils
  - condat-gridconv
  - condor
  - damnit
  - envmodules
  - euxfel-bunch-pattern
  - extra-data >= 1.14
  - extra-geom
  - extra-hed
  - findxfel
  - hdf5-vds-check
  - karabo-bridge
  - karabo_bridge_recorder
  - line-profiler
  - matplotlib-scalebar
  - metadata-client
  - metropc
  - nbclick
  - pasha >= 0.1.2
  - princess
