name: Docs - PR Merged

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  deployments: write

env:
  GIT_COMMITTER_NAME: github-actions[bot]
  GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com

jobs:
  remove-preview-files:
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.commit.outputs.hash }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Remove Preview
        run: |
          git rm -rf pr/${{ github.event.number }}

      - name: Commit and Push
        id: commit
        run: |
          git commit \
            -m "Remove Preview for PR#${{ github.event.number }}" \
            -m "${{ github.event.pull_request.head.sha }}"
          git push
          echo "hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      url: https://${{ github.repository_owner }}.github.io/${{github.event.repository.name}}/pr/${{ github.event.number }}
    needs: remove-preview-files
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ~~View preview here - ${{ env.url }}~~

            ~~Build for ${{ github.event.pull_request.head.sha }}~~

            Preview removed on merge with ${{ needs.remove-preview-files.outputs.hash }}
