name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/setup
        with:
          python-version: 3.8

      - run: poetry run poe docs gh-deploy --force

  rtd_webhook:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Trigger RTD User Documentation Webhook
        run: curl -X POST ${{ secrets.RTD_USER_DOCS_WEBHOOK_URL }} -d 'token=${{ secrets.RTD_USER_DOCS_WEBHOOK_SECRET }}'
