name: Docs - PR

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

env:
  GIT_COMMITTER_NAME: github-actions[bot]
  GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
  URL: https://${{ github.repository_owner }}.github.io/${{github.event.repository.name}}/pr/${{ github.event.number }}

jobs:
  build-and-upload:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/setup
        with:
          python-version: 3.8

      - run: poetry run poe docs build

      - uses: actions/upload-artifact@v4
        with:
          path: ./site

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-upload
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - uses: actions/download-artifact@v4

      - name: Add/Update Preview
        run: |
          mkdir -p pr
          rm -rf pr/${{ github.event.number }}
          mv artifact pr/${{ github.event.number }}

      - name: Commit and Push
        run: |
          git add --all pr/${{ github.event.number }}
          git clean -fdx
          git commit \
            -m "Preview for PR#${{ github.event.number }}" \
            -m "${{ github.event.pull_request.head.sha }}"
          git push

  comment-deployed:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: deploy
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Summarise Changes
        run: |
          mv gh-pages/pr . || mkdir -p pr/${{ github.event.number }}
          rm -rf */.nojekyll */.git */sitemap.xml */sitemap.xml.gz || true
          rm -rf **.css **.css.map **.js **.js.map || true
          {
            echo "View preview here - ${{ env.URL }} (build for ${{ github.event.pull_request.head.sha }})"
            echo ""
            echo "<details>"
            echo "<summary>Page Changes</summary>"
            echo ""
            echo "```diff"
            diff -bur ./gh-pages ./pr/${{ github.event.number }}
            echo "```"
            echo "</details>"
          } > COMMENT.md

          echo "View preview here - ${{ env.URL }}" > COMMENT.md
          echo "Build for ${{ github.event.pull_request.head.sha }}" >> COMMENT.md
          echo "" >> COMMENT.md
          echo "<details>" >> COMMENT.md
          echo "<summary>Page Changes</summary>" >> COMMENT.md
          echo "" >> COMMENT.md
          echo "```diff" >> COMMENT.md
          diff -bur ./gh-pages ./pr/${{ github.event.number }} >> COMMENT.md
          echo "```" >> COMMENT.md
          echo "</details>" >> COMMENT.md

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: COMMENT.md

  remove-preview-files:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    outputs:
      hash: ${{ steps.commit.outputs.hash }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Remove Preview
        run: |
          git rm -rf pr/${{ github.event.number }}

      - name: Commit and Push
        id: commit
        run: |
          git commit \
            -m "Remove Preview for PR#${{ github.event.number }}" \
            -m "${{ github.event.pull_request.head.sha }}"
          git push
          echo "hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

  comment-closed:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: remove-preview-files
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          message: |
            Preview removed on merge/PR close with ${{ needs.remove-preview-files.outputs.hash }}
